folder_in: /home/user/tst
folder_out: /home/user/out
folder_ext: /home/user/folder1
folder_ext3: /home/user/folder3
folder_bad: /home/user/folder2
count: 2
bs: 10K
#ip_user: 0.0.0.0
#user: user2
#pass: "1111"
local_path: /home/Seminar/user2/p7zip-full.deb
remote_path: /home/user2/p7zip-full.deb
package: p7zip-full
folder_stat: /home/user2/stat.txt
ta: zip
